### ISSUE TITLE
spanish translation

### ISSUE THREAD

**Issue by maasencioh** [pnpm/pnpm.github.io#2]
I'm a native spanish speaker, if you want I can contribute with that translation, but I don't know where to create the pull request

**Comment by zkochan** [comment]
@maasencioh awesome!

You can check the PR that added Brasil Portugues: https://github.com/pnpm/pnpm.github.io/pull/1

Basically, you have to add the new resources and run `npm run build` to regenerate the static site. I can document these steps if you want but probably only next week (I am on vacation this week). But if you do the translation I'll merge it fast because that's just a button click 😄
